name: release

# on: 
#   push:
#     branches:
#     - releases/v1.0

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: ncipollo/release-action@v1
      with:
        body: "publishing releases/v1.0"
        commit: "release"
        tag: "v1.0"
        token: ${{ secrets.GITHUB_TOKEN }}
   
